from models.base import Base
from models.pessoa import Pessoa
from models.cliente import Cliente
from models.funcionario import Funcionario
from models.fornecedor import Fornecedor
from models.material import Material
from models.comanda import Comanda
from models.pagamento import Pagamento
from models.consumo import Consumo
from models.recebimento import Recebimento
from models.consumo_has_material import ConsumoHasMaterial
from models.comanda_has_consumo import ComandaHasConsumo
from models.material_has_fornecedor import MaterialHasFornecedor
